"""DONE

Revision ID: 9f111829a9fb
Revises: 
Create Date: 2021-10-26 12:52:55.399316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f111829a9fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL-shortener',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=128), nullable=True),
    sa.Column('shorten_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL-shortener')
    # ### end Alembic commands ###
